### ISSUE TITLE
Add ability to add members

### ISSUE THREAD

**Issue by futurelucas4502** [futurelucas4502/management_console_mobile#10]
Use button in bottom right (like flutter boiler plate example) or in top right on appbar (either or but not both) to add a new member

**Comment by ghost** [comment]
I'll attempt this one

**Comment by futurelucas4502** [comment]
alright cool obviously leave room for the main body of the page so i can do #8

**Comment by ghost** [comment]
Created basic scaffold with a floating action button showing a plus button. I've also started the add members widget with a username and email fields. Just need to work out the selector

**Comment by futurelucas4502** [comment]
@harrisonelliott okay i added some code for editing members yesterday which has an example layout of the form which you could reuse in the add member view
